return function()
	require("mini.ai").setup()
	require("mini.bracketed").setup()
	require("mini.comment").setup()
	require("mini.cursorword").setup()
	require("mini.jump").setup()
	require("mini.jump2d").setup()
	require("mini.pairs").setup()

	require("aiecee.cfg.mini.base16")()
	require("aiecee.cfg.mini.clues")()
	require("aiecee.cfg.mini.hipatterns")()
	require("aiecee.cfg.mini.icons")()
	require("aiecee.cfg.mini.move")()
	require("aiecee.cfg.mini.statusline")()
	require("aiecee.cfg.mini.surround")()
end
