require("aiecee.config.code")
require("aiecee.config.completion")
require("aiecee.config.lsp").setup()
require("aiecee.config.ui")
require("aiecee.config.fterm")
require("aiecee.config.which-key")
require("aiecee.config.zen")
